import shortid from 'shortid';

const ACCOUNTS_DATA = [
  {
    id: shortid(),
    centerName: 'transition virtual mindshare',
    username: 'madelinesauer',
    password: 'auxiliary',
    contact: '1-933-639-3389 x041',
    email: 'a_b14@gmail.com',
    location: 'Moldova',
    viewPage: 1,
  },
  {
    id: shortid(),
    centerName: 'benchmark 24/7 platforms',
    username: 'rolandchristiansen',
    password: 'digital',
    contact: '523.691.9744 x246',
    email: 'a26@gmail.com',
    location: 'Sweden',
    viewPage: 2,
  },
  {
    id: shortid(),
    centerName: 'revolutionize wireless users',
    username: 'johnnyboehm',
    password: 'optical',
    contact: '920-763-2429 x78925',
    email: 'a.b62@gmail.com',
    location: 'San Marino',
    viewPage: 3,
  },
  {
    id: shortid(),
    centerName: 'engage out-of-the-box channels',
    username: 'deweydicki',
    password: 'open-source',
    contact: '493.566.1590',
    email: 'a.b@hotmail.com',
    location: 'Puerto Rico',
    viewPage: 4,
  },
  {
    id: shortid(),
    centerName: 'repurpose mission-critical vortals',
    username: "luciao'connell",
    password: 'digital',
    contact: '1-838-398-9051 x7200',
    email: 'a_b6@gmail.com',
    location: 'Canada',
    viewPage: 5,
  },
  {
    id: shortid(),
    centerName: 'visualize cross-platform technologies',
    username: 'alvinlockman',
    password: 'auxiliary',
    contact: '1-214-296-6393 x434',
    email: 'a44@hotmail.com',
    location: 'Estonia',
    viewPage: 6,
  },
  {
    id: shortid(),
    centerName: 'integrate collaborative portals',
    username: 'joannaprohaska',
    password: 'haptic',
    contact: '981.794.5598',
    email: 'a.b@hotmail.com',
    location: 'Germany',
    viewPage: 7,
  },
  {
    id: shortid(),
    centerName: 'engage collaborative action-items',
    username: 'mrs.joshuaheaney',
    password: 'primary',
    contact: '(287) 611-5286',
    email: 'a98@hotmail.com',
    location: 'Turks and Caicos Islands',
    viewPage: 8,
  },
  {
    id: shortid(),
    centerName: 'whiteboard 24/365 convergence',
    username: 'ms.juandouglas',
    password: 'online',
    contact: '413-754-2714',
    email: 'a16@yahoo.com',
    location: 'Iceland',
    viewPage: 9,
  },
  {
    id: shortid(),
    centerName: 'revolutionize viral partnerships',
    username: 'santiagokerluke',
    password: 'back-end',
    contact: '(414) 418-8630',
    email: 'a57@hotmail.com',
    location: 'Nepal',
    viewPage: 10,
  },
  {
    id: shortid(),
    centerName: 'redefine sticky architectures',
    username: 'elsaharris',
    password: 'auxiliary',
    contact: '(658) 728-3921 x579',
    email: 'a86@hotmail.com',
    location: 'Liechtenstein',
    viewPage: 11,
  },
  {
    id: shortid(),
    centerName: 'iterate intuitive supply-chains',
    username: 'corneliusfarrelljr.',
    password: 'online',
    contact: '285.361.2827',
    email: 'a.b71@hotmail.com',
    location: 'Algeria',
    viewPage: 12,
  },
  {
    id: shortid(),
    centerName: 'cultivate rich technologies',
    username: 'benfunk',
    password: 'multi-byte',
    contact: '1-267-624-4265',
    email: 'a_b@gmail.com',
    location: 'Myanmar',
    viewPage: 13,
  },
  {
    id: shortid(),
    centerName: 'monetize intuitive solutions',
    username: 'mr.claudiareynoldsv',
    password: 'mobile',
    contact: '1-341-538-7780 x86458',
    email: 'a.b@yahoo.com',
    location: 'Bouvet Island (Bouvetoya)',
    viewPage: 14,
  },
  {
    id: shortid(),
    centerName: 'embrace visionary experiences',
    username: 'elvirawilliamson',
    password: 'multi-byte',
    contact: '846-703-8627 x4856',
    email: 'a_b@gmail.com',
    location: 'Somalia',
    viewPage: 15,
  },
  {
    id: shortid(),
    centerName: 'enable granular solutions',
    username: 'lelafriesendds',
    password: '1080p',
    contact: '596.463.4760',
    email: 'a_b51@yahoo.com',
    location: 'French Guiana',
    viewPage: 16,
  },
  {
    id: shortid(),
    centerName: 'utilize out-of-the-box systems',
    username: 'melodyfahey',
    password: 'wireless',
    contact: '(638) 606-2766 x24425',
    email: 'a_b@hotmail.com',
    location: 'Ukraine',
    viewPage: 17,
  },
  {
    id: shortid(),
    centerName: 'incubate dynamic infomediaries',
    username: 'estelleankunding',
    password: 'cross-platform',
    contact: '367-389-2811',
    email: 'a_b@gmail.com',
    location: 'Estonia',
    viewPage: 18,
  },
  {
    id: shortid(),
    centerName: 'streamline scalable markets',
    username: 'dr.alexisrussel',
    password: 'redundant',
    contact: '961-422-8651 x763',
    email: 'a36@yahoo.com',
    location: 'Saint Vincent and the Grenadines',
    viewPage: 19,
  },
  {
    id: shortid(),
    centerName: 'facilitate clicks-and-mortar niches',
    username: 'charlenekreigerjr.',
    password: 'open-source',
    contact: '(491) 985-2483 x36519',
    email: 'a.b57@gmail.com',
    location: 'Bouvet Island (Bouvetoya)',
    viewPage: 20,
  },
  {
    id: shortid(),
    centerName: 'synergize visionary web services',
    username: 'mr.rafaelstark',
    password: 'bluetooth',
    contact: '332-358-9256 x233',
    email: 'a_b@hotmail.com',
    location: 'Saint Vincent and the Grenadines',
    viewPage: 21,
  },
  {
    id: shortid(),
    centerName: 'generate collaborative metrics',
    username: 'virgiladams',
    password: 'redundant',
    contact: '704-611-3861 x87166',
    email: 'a16@gmail.com',
    location: 'Belize',
    viewPage: 22,
  },
  {
    id: shortid(),
    centerName: 'embrace web-enabled models',
    username: 'dexterruecker',
    password: 'multi-byte',
    contact: '373-598-6310 x901',
    email: 'a_b9@yahoo.com',
    location: 'Niger',
    viewPage: 23,
  },
  {
    id: shortid(),
    centerName: 'utilize distributed paradigms',
    username: 'ms.rebeccalangoshdvm',
    password: 'online',
    contact: '922.567.7195 x95102',
    email: 'a13@hotmail.com',
    location: 'Qatar',
    viewPage: 24,
  },
  {
    id: shortid(),
    centerName: 'deliver customized metrics',
    username: 'mrs.armandoheaneyiii',
    password: 'cross-platform',
    contact: '894-901-1567 x46565',
    email: 'a74@gmail.com',
    location: 'Mali',
    viewPage: 25,
  },
  {
    id: shortid(),
    centerName: 'expedite vertical e-commerce',
    username: 'jeanbosco',
    password: 'optical',
    contact: '637.646.5966 x109',
    email: 'a.b92@yahoo.com',
    location: 'Timor-Leste',
    viewPage: 26,
  },
  {
    id: shortid(),
    centerName: 'evolve leading-edge e-markets',
    username: 'ryanmckenzie',
    password: 'redundant',
    contact: '1-828-661-9839 x28792',
    email: 'a.b2@yahoo.com',
    location: 'French Polynesia',
    viewPage: 27,
  },
  {
    id: shortid(),
    centerName: 'innovate frictionless portals',
    username: 'missjennyhodkiewicz',
    password: '1080p',
    contact: '234.261.2649',
    email: 'a.b52@hotmail.com',
    location: 'Macedonia',
    viewPage: 28,
  },
  {
    id: shortid(),
    centerName: 'enable back-end relationships',
    username: 'darylpaucek',
    password: 'haptic',
    contact: '(216) 617-8706 x2905',
    email: 'a_b@hotmail.com',
    location: 'Bangladesh',
    viewPage: 29,
  },
  {
    id: shortid(),
    centerName: 'innovate leading-edge architectures',
    username: 'kristinkoss',
    password: 'bluetooth',
    contact: '484.316.6302 x094',
    email: 'a_b88@yahoo.com',
    location: 'American Samoa',
    viewPage: 30,
  },
  {
    id: shortid(),
    centerName: 'morph revolutionary synergies',
    username: 'jocorkery',
    password: 'neural',
    contact: '1-728-586-7650 x873',
    email: 'a_b35@hotmail.com',
    location: 'Malawi',
    viewPage: 31,
  },
  {
    id: shortid(),
    centerName: 'aggregate value-added content',
    username: 'ms.tinakshlerin',
    password: 'multi-byte',
    contact: '454-276-6222 x410',
    email: 'a_b@gmail.com',
    location: 'Armenia',
    viewPage: 32,
  },
  {
    id: shortid(),
    centerName: 'integrate clicks-and-mortar metrics',
    username: 'morrisheaneyii',
    password: 'haptic',
    contact: '1-247-678-5285',
    email: 'a_b@hotmail.com',
    location: 'Nauru',
    viewPage: 33,
  },
  {
    id: shortid(),
    centerName: 'incentivize real-time ROI',
    username: "nicholaso'keefe",
    password: 'auxiliary',
    contact: '790-507-5874 x84896',
    email: 'a.b84@hotmail.com',
    location: 'Guinea',
    viewPage: 34,
  },
  {
    id: shortid(),
    centerName: 'deploy leading-edge web services',
    username: 'paulanicolasi',
    password: 'virtual',
    contact: '930.753.6627',
    email: 'a_b@gmail.com',
    location: 'Bulgaria',
    viewPage: 35,
  },
  {
    id: shortid(),
    centerName: 'extend visionary paradigms',
    username: 'candiceupton',
    password: 'wireless',
    contact: '1-859-442-9172 x50694',
    email: 'a.b71@yahoo.com',
    location: 'Indonesia',
    viewPage: 36,
  },
  {
    id: shortid(),
    centerName: 'harness open-source eyeballs',
    id: shortid(),
    password: 'cross-platform',
    contact: '1-293-599-1306',
    email: 'a58@hotmail.com',
    location: 'Bermuda',
    viewPage: 37,
  },
  {
    id: shortid(),
    centerName: 'exploit visionary deliverables',
    username: 'ms.celiahayes',
    password: 'mobile',
    contact: '(231) 315-4601 x828',
    email: 'a_b65@hotmail.com',
    location: 'Mauritius',
    viewPage: 38,
  },
  {
    id: shortid(),
    centerName: 'exploit 24/365 applications',
    username: 'bessiegislasonv',
    password: 'back-end',
    contact: '(954) 523-1105',
    email: 'a48@gmail.com',
    location: 'Cocos (Keeling) Islands',
    viewPage: 39,
  },
  {
    id: shortid(),
    centerName: 'drive cross-media solutions',
    username: 'maxinesimonisv',
    password: 'wireless',
    contact: '595-281-7290',
    email: 'a_b23@gmail.com',
    location: 'Brunei Darussalam',
    viewPage: 40,
  },
  {
    id: shortid(),
    centerName: 'leverage killer e-tailers',
    username: 'roxannesatterfield',
    password: 'haptic',
    contact: '778.345.2007 x49249',
    email: 'a_b@gmail.com',
    location: 'Monaco',
    viewPage: 41,
  },
  {
    id: shortid(),
    centerName: 'deploy transparent communities',
    username: 'ericstreich',
    password: 'redundant',
    contact: '900-594-7203',
    email: 'a87@hotmail.com',
    location: 'Iraq',
    viewPage: 42,
  },
  {
    id: shortid(),
    centerName: 'disintermediate transparent networks',
    username: 'arlenegraham',
    password: 'redundant',
    contact: '(499) 685-8415 x8218',
    email: 'a_b@yahoo.com',
    location: 'Jamaica',
    viewPage: 43,
  },
  {
    id: shortid(),
    centerName: 'revolutionize real-time action-items',
    username: 'evelynhudson',
    password: 'auxiliary',
    contact: '615-859-8986',
    email: 'a.b51@gmail.com',
    location: 'Tonga',
    viewPage: 44,
  },
  {
    id: shortid(),
    centerName: 'grow web-enabled niches',
    username: 'meganthiel',
    password: 'redundant',
    contact: '474-730-4157 x315',
    email: 'a89@yahoo.com',
    location: 'Lebanon',
    viewPage: 45,
  },
  {
    id: shortid(),
    centerName: 'cultivate plug-and-play networks',
    username: 'lilliekohlerii',
    id: shortid(),
    contact: '(928) 361-9067',
    email: 'a72@yahoo.com',
    location: 'Tonga',
    viewPage: 46,
  },
  {
    id: shortid(),
    centerName: 'architect enterprise supply-chains',
    username: 'carmenhegmanndvm',
    password: 'multi-byte',
    contact: '701-799-9731 x8906',
    email: 'a64@gmail.com',
    location: 'Grenada',
    viewPage: 47,
  },
  {
    id: shortid(),
    centerName: 'whiteboard vertical infrastructures',
    username: 'velmaanderson',
    password: 'neural',
    contact: '971.506.8688 x90507',
    email: 'a_b58@gmail.com',
    id: shortid(),
    viewPage: 48,
  },
  {
    id: shortid(),
    centerName: 'target revolutionary convergence',
    username: 'timcole',
    password: 'multi-byte',
    contact: '935.341.4139 x80007',
    email: 'a_b@gmail.com',
    location: 'Senegal',
    viewPage: 49,
  },
  {
    id: shortid(),
    centerName: 'seize back-end convergence',
    username: 'jeannettekrajcik',
    password: 'multi-byte',
    contact: '(830) 986-7982',
    email: 'a.b@hotmail.com',
    location: 'Bermuda',
    viewPage: 50,
  },
  {
    id: shortid(),
    centerName: 'grow bleeding-edge experiences',
    username: 'blancafriesen',
    password: 'optical',
    contact: '613-558-3270 x67125',
    email: 'a35@yahoo.com',
    location: 'Tokelau',
    viewPage: 51,
  },
  {
    id: shortid(),
    centerName: 'recontextualize synergistic users',
    username: 'stanleystiedemann',
    password: 'back-end',
    contact: '767-809-3451 x1671',
    email: 'a_b@yahoo.com',
    location: 'Jordan',
    viewPage: 52,
  },
  {
    id: shortid(),
    centerName: 'incentivize synergistic portals',
    username: 'jodibergstrom',
    password: 'haptic',
    contact: '237.294.2885',
    email: 'a.b58@yahoo.com',
    location: 'Kiribati',
    viewPage: 53,
  },
  {
    id: shortid(),
    centerName: 'reintermediate sticky vortals',
    username: 'romantremblayi',
    password: 'wireless',
    contact: '530.261.8221',
    email: 'a.b@yahoo.com',
    location: 'Anguilla',
    viewPage: 54,
  },
  {
    id: shortid(),
    id: shortid(),
    username: 'bryantwalter',
    password: 'primary',
    contact: '842.271.6614',
    email: 'a.b@hotmail.com',
    location: 'Comoros',
    viewPage: 55,
  },
  {
    id: shortid(),
    centerName: 'cultivate viral schemas',
    username: 'carolhammes',
    password: '1080p',
    contact: '314.975.7972 x422',
    email: 'a41@yahoo.com',
    location: 'Marshall Islands',
    viewPage: 56,
  },
  {
    id: shortid(),
    centerName: 'matrix 24/7 synergies',
    username: 'mauriceshanahan',
    password: 'primary',
    contact: '550.473.1945',
    email: 'a.b60@yahoo.com',
    location: 'Burkina Faso',
    viewPage: 57,
  },
  {
    id: shortid(),
    centerName: 'revolutionize cross-platform action-items',
    username: 'missmanuelwitting',
    password: 'optical',
    contact: '(546) 876-9815 x813',
    email: 'a_b@gmail.com',
    location: 'Papua New Guinea',
    viewPage: 58,
  },
  {
    id: shortid(),
    centerName: 'repurpose magnetic functionalities',
    username: 'dwightkertzmann',
    id: shortid(),
    contact: '(322) 292-1023 x625',
    email: 'a.b@yahoo.com',
    location: 'Jersey',
    viewPage: 59,
  },
  {
    id: shortid(),
    centerName: 'strategize killer solutions',
    username: 'suehalvorsondvm',
    id: shortid(),
    contact: '427.701.1353 x326',
    email: 'a.b@yahoo.com',
    location: 'South Georgia and the South Sandwich Islands',
    viewPage: 60,
  },
  {
    id: shortid(),
    centerName: 'brand leading-edge solutions',
    username: 'mrs.adamwhite',
    password: 'mobile',
    contact: '571-342-8024',
    email: 'a50@gmail.com',
    location: 'Jamaica',
    viewPage: 61,
  },
  {
    id: shortid(),
    centerName: 'cultivate ubiquitous paradigms',
    username: 'angelaraynormd',
    password: 'back-end',
    contact: '882-386-9918 x53540',
    email: 'a.b25@hotmail.com',
    location: 'Virgin Islands, U.S.',
    viewPage: 62,
  },
  {
    id: shortid(),
    centerName: 'architect extensible technologies',
    username: 'billmarks',
    password: 'mobile',
    contact: '499.293.5292',
    email: 'a_b@yahoo.com',
    location: 'Burundi',
    viewPage: 63,
  },
  {
    id: shortid(),
    centerName: 'aggregate holistic solutions',
    username: 'timothygerhold',
    password: 'haptic',
    contact: '1-841-887-7344 x924',
    email: 'a.b44@hotmail.com',
    location: 'Netherlands',
    viewPage: 64,
  },
  {
    id: shortid(),
    centerName: 'grow revolutionary channels',
    username: 'johnathanullrich',
    password: 'open-source',
    contact: '485-956-5024',
    email: 'a23@hotmail.com',
    location: 'Bermuda',
    viewPage: 65,
  },
  {
    id: shortid(),
    centerName: 'leverage e-business deliverables',
    username: 'monarunolfsdottir',
    password: 'multi-byte',
    contact: '841-753-3888 x296',
    email: 'a.b21@gmail.com',
    location: 'Uruguay',
    viewPage: 66,
  },
  {
    id: shortid(),
    centerName: 'maximize transparent e-markets',
    username: 'marlonlegros',
    password: 'primary',
    contact: '812.613.8604 x7910',
    email: 'a.b@hotmail.com',
    location: 'Libyan Arab Jamahiriya',
    viewPage: 67,
  },
  {
    id: shortid(),
    centerName: 'empower bleeding-edge convergence',
    username: 'mr.alexrobel',
    password: 'cross-platform',
    contact: '557-973-4743',
    email: 'a_b@gmail.com',
    location: 'Panama',
    viewPage: 68,
  },
  {
    id: shortid(),
    centerName: 'synthesize granular mindshare',
    username: 'mrs.elviragibson',
    password: 'auxiliary',
    contact: '561.606.5950 x6477',
    email: 'a.b81@hotmail.com',
    location: 'Virgin Islands, U.S.',
    viewPage: 69,
  },
  {
    id: shortid(),
    centerName: 'orchestrate scalable e-commerce',
    username: 'whitneyherzog',
    id: shortid(),
    contact: '281-817-4593',
    email: 'a_b@gmail.com',
    location: 'American Samoa',
    viewPage: 70,
  },
  {
    id: shortid(),
    centerName: 'utilize cross-media solutions',
    username: 'brentchristiansen',
    password: 'mobile',
    contact: '(854) 498-8023 x271',
    email: 'a65@hotmail.com',
    location: 'New Zealand',
    viewPage: 71,
  },
  {
    id: shortid(),
    centerName: 'target robust solutions',
    username: 'seanschumm',
    password: 'digital',
    contact: '1-610-254-6341 x9984',
    email: 'a.b73@hotmail.com',
    location: 'Sweden',
    viewPage: 72,
  },
  {
    id: shortid(),
    centerName: 'cultivate distributed metrics',
    username: 'sallyhyatt',
    password: 'neural',
    contact: '(613) 369-1428',
    email: 'a_b94@gmail.com',
    location: 'Malawi',
    viewPage: 73,
  },
  {
    id: shortid(),
    centerName: 'embrace web-enabled experiences',
    username: 'petemcglynn',
    password: 'mobile',
    contact: '398-775-3145',
    email: 'a.b7@gmail.com',
    location: 'Latvia',
    viewPage: 74,
  },
  {
    id: shortid(),
    centerName: 'whiteboard one-to-one paradigms',
    username: "beckyo'hara",
    password: 'auxiliary',
    contact: '(662) 323-8931 x207',
    email: 'a.b68@yahoo.com',
    location: 'Somalia',
    viewPage: 75,
  },
  {
    id: shortid(),
    centerName: 'generate interactive solutions',
    username: 'pamhermannjr.',
    password: 'redundant',
    contact: '953-943-6604 x0910',
    email: 'a_b63@yahoo.com',
    location: 'Costa Rica',
    viewPage: 76,
  },
  {
    id: shortid(),
    centerName: 'incubate sexy markets',
    id: shortid(),
    password: 'open-source',
    contact: '745.846.6811',
    email: 'a_b74@gmail.com',
    location: 'Niue',
    viewPage: 77,
  },
  {
    id: shortid(),
    centerName: 'morph vertical models',
    username: 'stellawisokyiii',
    password: 'primary',
    contact: '859-483-4791',
    email: 'a_b@yahoo.com',
    location: 'Ireland',
    viewPage: 78,
  },
  {
    id: shortid(),
    centerName: 'engineer plug-and-play functionalities',
    username: 'juliabreitenberg',
    password: 'haptic',
    contact: '1-821-498-6556',
    email: 'a.b15@gmail.com',
    location: 'Palestinian Territory',
    viewPage: 79,
  },
  {
    id: shortid(),
    centerName: 'synthesize mission-critical communities',
    username: 'miltoneffertz',
    password: 'redundant',
    contact: '1-365-224-9131',
    email: 'a.b81@yahoo.com',
    location: 'Congo',
    viewPage: 80,
  },
  {
    id: shortid(),
    centerName: 'optimize end-to-end e-commerce',
    username: 'angelosanford',
    id: shortid(),
    contact: '(284) 766-9632',
    email: 'a_b@gmail.com',
    location: 'Cook Islands',
    viewPage: 81,
  },
  {
    id: shortid(),
    centerName: 'architect innovative solutions',
    username: 'javiertreutel',
    password: 'mobile',
    contact: '629-309-2906',
    email: 'a1@yahoo.com',
    location: 'Guernsey',
    viewPage: 82,
  },
  {
    id: shortid(),
    centerName: 'streamline ubiquitous infomediaries',
    username: 'wilbertquigley',
    password: 'wireless',
    contact: '1-246-921-1073',
    email: 'a_b44@hotmail.com',
    location: 'Vanuatu',
    viewPage: 83,
  },
  {
    id: shortid(),
    centerName: 'visualize robust ROI',
    username: 'rodneydicki',
    id: shortid(),
    contact: '598-680-7358',
    email: 'a.b@hotmail.com',
    location: 'Jersey',
    viewPage: 84,
  },
  {
    id: shortid(),
    centerName: 'optimize rich interfaces',
    username: 'dexterglover',
    password: '1080p',
    contact: '709-549-8215 x688',
    email: 'a.b@gmail.com',
    location: 'Northern Mariana Islands',
    viewPage: 85,
  },
  {
    id: shortid(),
    centerName: 'whiteboard dynamic communities',
    username: 'mamiedibbert',
    password: 'virtual',
    contact: '1-863-580-1055',
    email: 'a_b@hotmail.com',
    location: 'Virgin Islands, U.S.',
    viewPage: 86,
  },
  {
    id: shortid(),
    centerName: 'embrace out-of-the-box e-business',
    username: 'ramirohodkiewicz',
    password: 'cross-platform',
    contact: '738-548-0212 x51080',
    email: 'a_b@hotmail.com',
    location: 'Iraq',
    viewPage: 87,
  },
  {
    id: shortid(),
    centerName: 'synthesize rich applications',
    username: 'theodorecollins',
    password: 'primary',
    contact: '860.566.6586 x56192',
    email: 'a_b@hotmail.com',
    location: 'Monaco',
    viewPage: 88,
  },
  {
    id: shortid(),
    centerName: 'reintermediate cross-platform supply-chains',
    username: 'gustavobrakus',
    password: 'cross-platform',
    contact: '(808) 662-0818 x515',
    email: 'a.b@gmail.com',
    location: 'Georgia',
    viewPage: 89,
  },
  {
    id: shortid(),
    centerName: 'benchmark extensible eyeballs',
    username: 'emmettzboncak',
    password: 'bluetooth',
    contact: '911-828-8203 x124',
    email: 'a_b@hotmail.com',
    location: 'Qatar',
    viewPage: 90,
  },
  {
    id: shortid(),
    centerName: 'envisioneer visionary ROI',
    username: 'rosehilll',
    password: 'auxiliary',
    contact: '1-749-597-0810',
    email: 'a69@yahoo.com',
    location: 'Angola',
    viewPage: 91,
  },
  {
    id: shortid(),
    centerName: 'grow killer networks',
    username: 'dominickprosacco',
    password: 'mobile',
    contact: '(433) 861-5343',
    email: 'a10@gmail.com',
    location: 'Lesotho',
    viewPage: 92,
  },
  {
    id: shortid(),
    centerName: 'maximize next-generation initiatives',
    username: 'shelleynolan',
    password: 'digital',
    contact: '720.471.1639',
    email: 'a.b19@hotmail.com',
    location: 'Somalia',
    viewPage: 93,
  },
  {
    id: shortid(),
    centerName: 'repurpose frictionless applications',
    id: shortid(),
    password: 'bluetooth',
    contact: '711.846.3934',
    email: 'a.b@yahoo.com',
    location: 'Malaysia',
    viewPage: 94,
  },
  {
    id: shortid(),
    centerName: 'target compelling e-markets',
    username: 'martastrosin',
    password: 'redundant',
    contact: '1-851-274-1919 x57593',
    email: 'a.b11@yahoo.com',
    location: 'Netherlands',
    viewPage: 95,
  },
  {
    id: shortid(),
    centerName: 'unleash frictionless systems',
    username: 'michelebeier',
    password: 'primary',
    contact: '1-702-300-2567 x2895',
    email: 'a_b36@hotmail.com',
    location: 'Chad',
    viewPage: 96,
  },
  {
    id: shortid(),
    centerName: 'facilitate front-end markets',
    id: shortid(),
    password: 'haptic',
    contact: '367.397.4377 x4215',
    email: 'a32@yahoo.com',
    location: 'Timor-Leste',
    viewPage: 97,
  },
  {
    id: shortid(),
    centerName: 'transform robust models',
    username: 'waynewest',
    password: 'open-source',
    contact: '(443) 810-9439 x24525',
    email: 'a.b87@yahoo.com',
    location: 'Comoros',
    viewPage: 98,
  },
  {
    id: shortid(),
    centerName: 'e-enable value-added communities',
    username: 'janegusikowski',
    password: 'back-end',
    contact: '(654) 660-9042 x5445',
    email: 'a.b36@gmail.com',
    location: 'Greece',
    viewPage: 99,
  },
  {
    id: shortid(),
    centerName: 'whiteboard bricks-and-clicks e-business',
    username: 'martinruntemd',
    password: 'bluetooth',
    contact: '492.457.1721',
    email: 'a19@gmail.com',
    location: 'Pakistan',
    viewPage: 100,
  },
];

export default ACCOUNTS_DATA;
