const CAMERAS = [
  {
    id: 'SUFDhzHug',
    name: 'brand proactive eyeballs',
    ip: '131.235.19.109',
    enable: false,
    blank: false,
  },
  {
    id: 'JZ6shp0qiY',
    name: 'deliver granular supply-chains',
    ip: '17.193.199.25',
    enable: false,
    blank: false,
  },
  {
    id: 'TRHhH1osGO',
    name: 'strategize one-to-one applications',
    ip: '224.1.190.104',
    enable: false,
    blank: true,
  },
  {
    id: 'wjLYUFI6lc',
    name: 'embrace vertical technologies',
    ip: '56.169.87.192',
    enable: true,
    blank: true,
  },
  {
    id: 'Ze4QPPpOEE',
    name: 'orchestrate best-of-breed content',
    ip: '145.141.111.222',
    enable: true,
    blank: true,
  },
  {
    id: 'EvwKzlEdsC',
    name: 'streamline best-of-breed synergies',
    ip: '84.140.27.114',
    enable: true,
    blank: false,
  },
  {
    id: 'QgP156SAEx',
    name: 'target front-end ROI',
    ip: '50.27.187.206',
    enable: true,
    blank: true,
  },
  {
    id: 'sAOQ0nn5kU',
    name: 'deliver compelling metrics',
    ip: '24.97.35.246',
    enable: false,
    blank: false,
  },
  {
    id: 'MW4qXKT6zP',
    name: 'empower cross-media synergies',
    ip: '15.63.21.98',
    enable: false,
    blank: false,
  },
  {
    id: 'j_CakUKG4c',
    name: 'redefine cutting-edge ROI',
    ip: '247.231.177.214',
    enable: true,
    blank: false,
  },
  {
    id: 'c7ZROso1q6',
    name: 'innovate 24/365 web services',
    ip: '213.225.95.219',
    enable: false,
    blank: false,
  },
  {
    id: 'hpTWbRNw2Q',
    name: 'cultivate user-centric bandwidth',
    ip: '78.121.71.18',
    enable: false,
    blank: true,
  },
  {
    id: '-YONYiPIPh',
    name: 'aggregate impactful architectures',
    ip: '31.19.38.202',
    enable: true,
    blank: false,
  },
  {
    id: 'JHlOPWuWPJ',
    name: 'cultivate global ROI',
    ip: '251.89.231.37',
    enable: false,
    blank: true,
  },
  {
    id: '0ep_F-4Y0-',
    name: 'embrace mission-critical paradigms',
    ip: '98.161.113.236',
    enable: false,
    blank: false,
  },
  {
    id: 'tPMj4mcC-J',
    name: 'mesh interactive methodologies',
    ip: '99.22.34.58',
    enable: false,
    blank: false,
  },
  {
    id: 'OrfFAmYRAjm',
    name: 'iterate transparent infomediaries',
    ip: '20.109.39.32',
    enable: false,
    blank: true,
  },
  {
    id: 'ynxrfwQa6rA',
    name: 'synthesize value-added ROI',
    ip: '233.57.15.105',
    enable: false,
    blank: false,
  },
  {
    id: 'gPd2qrujEj_',
    name: 'drive seamless platforms',
    ip: '175.77.88.60',
    enable: true,
    blank: false,
  },
  {
    id: 'hbD9Meac7ad',
    name: 'matrix frictionless markets',
    ip: '152.58.187.1',
    enable: false,
    blank: true,
  },
  {
    id: 'boGrshEI_jg',
    name: 'reinvent rich infrastructures',
    ip: '106.96.202.124',
    enable: false,
    blank: false,
  },
  {
    id: 'ZUDTKA3AIpK',
    name: 'facilitate mission-critical infrastructures',
    ip: '20.49.58.107',
    enable: true,
    blank: false,
  },
  {
    id: 'D-C_CkX-bVr',
    name: 'optimize world-class synergies',
    ip: '65.165.207.87',
    enable: false,
    blank: true,
  },
  {
    id: 'PgF1dmEXWQu',
    name: 'evolve plug-and-play systems',
    ip: '49.133.144.135',
    enable: false,
    blank: false,
  },
  {
    id: 'ZX1MC0B-yZo',
    name: 'target front-end paradigms',
    ip: '135.212.54.200',
    enable: true,
    blank: false,
  },
];

export default CAMERAS;
